apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shinhan-tls
  namespace: istio-system
spec:
  dnsNames:
  - v1.shinhan.dudaji.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  renewBefore: 360h0m0s
  secretName: shinhan-tls