# config.yaml
device:
  type: GPU
  model: A100
  count: 1

model:
  name: llama3.3:70b
  quantization: Q4_K_M
  calibration: base

evaluation:
  task: translation
  metrics:
    BLEU: true
    METEOR: true
    BERTScore: true
    tps: true
    power_consumption: true
    memory_usage: false
  output_dir: ../result/translate